"""Scoring an interview against its rubric — a port of `server/services/scoring.ts`.

**The overall score is computed here, never taken from the model.** The model scores
each answer against each KPI; the weighting, averaging and the resulting
recommendation are arithmetic done in this file. That separation is the point: a
recruiter's rubric weights are a policy decision, and a model asked for "an overall
score" would quietly apply its own.

Three paths, in order of preference:

* **Model-scored** — per-KPI scores per question, from Gemini.
* **Heuristic** — no key configured. Deterministic, based on answer LENGTH only, and it
  says so in the summary and sets `degraded`. It exists so a deployment without a key
  still produces a report rather than an error.
* **Not evaluated** — no candidate answers were captured at all. This one is not a
  fallback but a refusal: see `not_evaluated_report`.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from app.config import Settings
from app.web.services import conversation, gemini, signals

logger = logging.getLogger("web.scoring")

RECOMMENDATIONS = ("strong_yes", "yes", "maybe", "no")

# Tracks whose questions come from a conversation rather than fixed slots.
CONVERSATION_TRACKS = ("chatbot", "video_avatar", "voice", "video", "two_way")

HEURISTIC_FEEDBACK = (
    "Heuristic placeholder — add a GEMINI_API_KEY for substantive, content-aware feedback."
)
NO_ANSWER_FEEDBACK = "No answer was provided for this question."
NO_ANSWER_CAPTURED_FEEDBACK = "No answer was captured for this question."

HEURISTIC_SUMMARY = (
    "Generated by the heuristic fallback (no Gemini key configured). Scores reflect "
    "answer length only, not content quality."
)

NOT_EVALUATED_SUMMARY = (
    "No candidate answers were captured for this interview, so it was not evaluated. "
    "This usually means the interview audio or transcript was not recorded (the call may "
    "have ended early, or capture failed). Please ask the candidate to retake the "
    "interview, or check the avatar/voice configuration in Settings."
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def clamp(value: object) -> int:
    """A 0-100 integer. Anything unusable becomes 0."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return 0
    return max(0, min(100, round(value)))


def enabled_kpis(rubric: dict) -> list[dict]:
    return [kpi for kpi in (rubric or {}).get("kpis") or [] if kpi.get("enabled")]


# ── the arithmetic ────────────────────────────────────────────────────────────


def average_kpis(rubric: dict, per_question: list[dict]) -> dict[str, int]:
    """Each enabled KPI's mean across the questions that scored it.

    A question with no score for a KPI is EXCLUDED from that KPI's average rather than
    counted as zero — an unanswered question already drags the average down through its
    own zeros, and counting a missing score again would penalise it twice.
    """
    averages: dict[str, int] = {}
    for kpi in enabled_kpis(rubric):
        values = [
            entry["kpiScores"][kpi["id"]]
            for entry in per_question
            if isinstance(entry.get("kpiScores"), dict)
            and isinstance(entry["kpiScores"].get(kpi["id"]), (int, float))
            and not isinstance(entry["kpiScores"].get(kpi["id"]), bool)
        ]
        averages[kpi["id"]] = round(sum(values) / len(values)) if values else 0
    return averages


def weighted_overall(rubric: dict, kpi_averages: dict[str, int]) -> int:
    """The overall score: enabled KPI weights, normalised, applied to their averages.

    Normalised so the weights express RELATIVE importance rather than needing to sum to
    anything: a recruiter who sets three KPIs to weight 2 gets the same result as three
    at weight 1, which is what they meant.

    Zero when no KPI carries weight — a rubric with everything disabled has expressed no
    opinion, and inventing a number would be worse than reporting none.
    """
    weighted = [
        kpi
        for kpi in enabled_kpis(rubric)
        if isinstance(kpi.get("weight"), (int, float))
        and not isinstance(kpi.get("weight"), bool)
        and kpi["weight"] > 0
    ]
    total_weight = sum(kpi["weight"] for kpi in weighted)
    if total_weight == 0:
        return 0

    return round(
        sum(
            (kpi_averages.get(kpi["id"]) or 0) * kpi["weight"] / total_weight
            for kpi in weighted
        )
    )


def recommendation_for(overall: int) -> str:
    """The band an overall score falls in.

    Thresholds, not a model judgment, so two candidates with the same score always get
    the same recommendation.
    """
    if overall >= 80:
        return "strong_yes"
    if overall >= 65:
        return "yes"
    if overall >= 50:
        return "maybe"
    return "no"


def _recommendation(raw: object, overall: int) -> str:
    """The model's recommendation when it is one of ours, else derived from the score."""
    return raw if raw in RECOMMENDATIONS else recommendation_for(overall)


# ── the heuristic ─────────────────────────────────────────────────────────────


def _hash(text: str) -> int:
    """FNV-1a, matching the Express implementation.

    Used only to spread the heuristic scores apart deterministically. Hand-rolled rather
    than `hash()` because Python's is randomised per process, which would make the
    fallback report change between restarts for the same answers.
    """
    value = 2166136261
    for char in text:
        value ^= ord(char)
        value = (value * 16777619) & 0xFFFFFFFF
    return abs(value)


def heuristic_score(answer: str, kpi_id: str) -> int:
    """A length-based score. Zero for no answer.

    Deliberately crude and openly labelled as such: it exists so a deployment with no
    Gemini key still produces a usable-looking report shape, NOT so it can stand in for
    judgment. The spread keeps every KPI from showing an identical number, which would
    read as a real assessment that happened to agree.
    """
    words = len(answer.split())
    if words == 0:
        return 0
    base = min(90, 45 + round(min(words, 180) / 4))
    spread = (_hash(f"{kpi_id}:{answer[:40]}") % 17) - 8
    return clamp(base + spread)


# ── report assembly ───────────────────────────────────────────────────────────


def _report(
    session: dict,
    rubric: dict,
    per_question: list[dict],
    *,
    summary: str,
    strengths: list[str] | None = None,
    improvements: list[str] | None = None,
    recommendation: object = None,
    degraded: bool = False,
    not_evaluated: bool = False,
) -> dict:
    kpi_averages = average_kpis(rubric, per_question)
    overall = weighted_overall(rubric, kpi_averages)

    report: dict = {
        "sessionId": session.get("id"),
        "perQuestion": per_question,
        "kpiAverages": kpi_averages,
        "overallScore": overall,
        "summary": summary,
        "generatedAt": _now(),
    }
    if strengths:
        report["strengths"] = strengths
    if improvements:
        report["improvements"] = improvements
    if degraded:
        report["degraded"] = True
    if not_evaluated:
        # No recommendation at all: see `not_evaluated_report`.
        report["notEvaluated"] = True
        report["overallScore"] = 0
    else:
        report["recommendation"] = _recommendation(recommendation, overall)
    return report


def not_evaluated_report(session: dict, template: dict) -> dict:
    """An honest report for an interview where nothing was captured.

    NOT a zero score. A conversation whose transcript never arrived — a dropped call, a
    failed capture — has produced no evidence, and a report showing 0 with a "no"
    recommendation is a judgment nobody made. This keeps the planned questions visible,
    omits the recommendation entirely, and sets `notEvaluated` so the UI can say so.

    It also short-circuits the model: asked to evaluate an empty transcript, Gemini
    returns a fluent "no transcript was provided" summary alongside zero scores, which
    reads exactly like a real assessment.
    """
    per_question = [
        {"questionId": f"q{index}", "kpiScores": {}, "feedback": NO_ANSWER_CAPTURED_FEEDBACK}
        for index, _ in enumerate(session.get("questions") or [])
    ]
    return _report(
        session,
        template.get("rubric") or {},
        per_question,
        summary=NOT_EVALUATED_SUMMARY,
        not_evaluated=True,
    )


def assemble_from_model(session: dict, template: dict, raw: dict) -> dict:
    """A fixed-slot report from the model's per-question scores.

    Scores for KPIs that are not enabled are DISCARDED rather than stored: a model that
    invents a KPI id, or scores one the recruiter switched off, must not influence the
    average.
    """
    rubric = template.get("rubric") or {}
    allowed = {kpi["id"] for kpi in enabled_kpis(rubric)}
    by_id = {
        entry.get("questionId"): entry
        for entry in raw.get("perQuestion") or []
        if isinstance(entry, dict)
    }

    per_question = []
    for question in session.get("questions") or []:
        match = by_id.get(question.get("id")) or {}
        kpi_scores = {
            score["kpiId"]: clamp(score.get("score"))
            for score in match.get("scores") or []
            if isinstance(score, dict) and score.get("kpiId") in allowed
        }
        per_question.append(
            {
                "questionId": question.get("id"),
                "kpiScores": kpi_scores,
                "feedback": match.get("feedback") or "No feedback returned.",
            }
        )

    return _report(
        session,
        rubric,
        per_question,
        summary=raw.get("summary") or "No summary returned.",
        strengths=raw.get("strengths") if isinstance(raw.get("strengths"), list) else None,
        improvements=raw.get("improvements") if isinstance(raw.get("improvements"), list) else None,
        recommendation=raw.get("recommendation"),
    )


def assemble_conversation_from_model(session: dict, template: dict, raw: dict) -> dict:
    """A conversation report, keyed by question INDEX rather than id.

    A conversation's questions are identified by position in the transcript — there are
    no stored question records to carry ids — so the model is asked for indices and the
    groups are matched on those.
    """
    rubric = template.get("rubric") or {}
    allowed = {kpi["id"] for kpi in enabled_kpis(rubric)}
    by_index = {
        entry.get("questionIndex"): entry
        for entry in raw.get("perQuestion") or []
        if isinstance(entry, dict)
    }

    per_question = []
    for group in conversation.primary_question_groups(session):
        match = by_index.get(group["index"]) or {}
        kpi_scores = {
            score["kpiId"]: clamp(score.get("score"))
            for score in match.get("scores") or []
            if isinstance(score, dict) and score.get("kpiId") in allowed
        }
        per_question.append(
            {
                "questionId": f"q{group['index']}",
                "kpiScores": kpi_scores,
                "feedback": match.get("feedback") or "No feedback returned.",
            }
        )

    return _report(
        session,
        rubric,
        per_question,
        summary=raw.get("summary") or "No summary returned.",
        strengths=raw.get("strengths") if isinstance(raw.get("strengths"), list) else None,
        improvements=raw.get("improvements") if isinstance(raw.get("improvements"), list) else None,
        recommendation=raw.get("recommendation"),
    )


def heuristic_report(session: dict, template: dict) -> dict:
    """The fixed-slot fallback. Length-based, and labelled as such."""
    rubric = template.get("rubric") or {}
    kpis = enabled_kpis(rubric)

    per_question = []
    for question in session.get("questions") or []:
        answer = question.get("answerText") or ""
        per_question.append(
            {
                "questionId": question.get("id"),
                "kpiScores": {kpi["id"]: heuristic_score(answer, kpi["id"]) for kpi in kpis},
                "feedback": HEURISTIC_FEEDBACK if answer.strip() else NO_ANSWER_FEEDBACK,
            }
        )

    return _report(session, rubric, per_question, summary=HEURISTIC_SUMMARY, degraded=True)


def heuristic_conversation_report(session: dict, template: dict) -> dict:
    """The conversation fallback, over the grouped transcript."""
    rubric = template.get("rubric") or {}
    kpis = enabled_kpis(rubric)

    per_question = []
    for group in conversation.primary_question_groups(session):
        answer = group["answer"]
        per_question.append(
            {
                "questionId": f"q{group['index']}",
                "kpiScores": {kpi["id"]: heuristic_score(answer, kpi["id"]) for kpi in kpis},
                "feedback": (
                    "Heuristic placeholder — add a GEMINI_API_KEY for content-aware feedback."
                    if answer.strip()
                    else "No answer was provided."
                ),
            }
        )

    return _report(
        session,
        rubric,
        per_question,
        summary=(
            "Generated by the heuristic fallback (no Gemini key). Scores reflect answer "
            "length only."
        ),
        degraded=True,
    )


# ── prompts ───────────────────────────────────────────────────────────────────


def _rubric_text(kpis: list[dict]) -> str:
    return "\n".join(
        f"- {kpi['id']} ({kpi.get('label') or kpi['id']}): {kpi.get('description') or ''}"
        for kpi in kpis
    )


def _score_schema(*, by_index: bool) -> dict:
    """The response shape. `by_index` for conversations, question id for fixed slots."""
    key = "questionIndex" if by_index else "questionId"
    return {
        "type": "object",
        "properties": {
            "perQuestion": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        key: {"type": "number" if by_index else "string"},
                        "scores": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "kpiId": {"type": "string"},
                                    "score": {"type": "number"},
                                },
                                "required": ["kpiId", "score"],
                            },
                        },
                        "feedback": {"type": "string"},
                    },
                    "required": [key, "scores", "feedback"],
                },
            },
            "summary": {"type": "string"},
            "strengths": {"type": "array", "items": {"type": "string"}},
            "improvements": {"type": "array", "items": {"type": "string"}},
            "recommendation": {"type": "string", "enum": list(RECOMMENDATIONS)},
        },
        "required": ["perQuestion", "summary", "recommendation"],
    }


def build_fixed_prompt(session: dict, kpis: list[dict]) -> str:
    """The prompt for a fixed-slot interview.

    It carries each question's ideal-answer notes so the model scores against what the
    recruiter was looking for, and says "judging only what the candidate actually said"
    because a model given a rubric will otherwise credit an answer for what it implies.
    """
    transcript = "\n".join(
        f"Q{index + 1} [id:{question.get('id')}] ({question.get('category') or 'general'}): "
        f"{question.get('text') or ''}\n"
        f"Ideal-answer notes: {question.get('idealAnswerNotes') or '—'}\n"
        f"Candidate answer: {(question.get('answerText') or '').strip() or '(no answer given)'}\n"
        for index, question in enumerate(session.get("questions") or [])
    )
    ids = ", ".join(kpi["id"] for kpi in kpis)

    return f"""You are a fair but rigorous interview scorer. Score each answer against the rubric KPIs on a 0–100 scale, judging only what the candidate actually said.
Use ONLY these KPI ids: {ids}.

RUBRIC:
{_rubric_text(kpis)}

TRANSCRIPT:
{transcript}

For each question return its exact questionId, a score (0–100) for every KPI id listed above, and one or two sentences of specific feedback. Then provide an overall summary covering strengths and improvement areas, and a recommendation that is exactly one of: strong_yes, yes, maybe, no."""


def build_conversation_prompt(session: dict, kpis: list[dict]) -> str:
    """The prompt for a conversational interview.

    The transcript is passed RAW rather than pre-grouped, with follow-ups marked, and the
    model is told to fold follow-ups into their parent question's score. A model that saw
    only the grouped answers would lose the interviewer's probing, which is often what
    reveals whether an answer held up.
    """
    transcript = "\n".join(
        f"{'INTERVIEWER' if turn.get('role') == 'interviewer' else 'CANDIDATE'}"
        + (
            f" [q{turn['questionIndex']}{' · follow-up' if turn.get('isFollowUp') else ''}]"
            if isinstance(turn.get("questionIndex"), int)
            and not isinstance(turn.get("questionIndex"), bool)
            else ""
        )
        + f": {turn.get('content') or ''}"
        for turn in session.get("transcript") or []
    )
    ids = ", ".join(kpi["id"] for kpi in kpis)

    return f"""You are a fair but rigorous interview scorer. Below is a conversational interview transcript. Score each PRIMARY question (identified by its q-index) on a 0–100 scale against the rubric KPIs, judging only what the candidate actually said (fold any follow-ups into that question's score).
Use ONLY these KPI ids: {ids}.

RUBRIC:
{_rubric_text(kpis)}

TRANSCRIPT:
{transcript}

For each primary question return its questionIndex, a score (0–100) for every KPI id, and one or two sentences of specific feedback. Then give an overall summary, 2–4 concise strengths, 2–4 concise improvement areas, and a recommendation that is exactly one of: strong_yes, yes, maybe, no."""


# ── entry point ───────────────────────────────────────────────────────────────


async def score_session(settings: Settings, session: dict, template: dict) -> dict:
    """The report for a finished session. Never raises.

    Falls back rather than failing: a recruiter with a degraded report can still act, and
    a session that produced no report at all looks like the interview was lost.
    """
    import json

    if session.get("track") == "essay":
        # Not this function's conversation/fixed-slot machinery — essay has its
        # own prompt, rubric and injection-fencing. See essay_evaluation.py's
        # module docstring for why it still ends in the shape this file defines.
        from app.web.services import essay_evaluation

        return await essay_evaluation.evaluate_essay(settings, session)

    rubric = template.get("rubric") or {}
    kpis = enabled_kpis(rubric)
    is_conversation = session.get("track") in CONVERSATION_TRACKS

    if is_conversation and not conversation.has_any_answer(session):
        return not_evaluated_report(session, template)

    if kpis and await gemini.is_enabled(settings):
        try:
            text = await gemini.generate_text(
                settings,
                contents=[
                    {
                        "role": "user",
                        "parts": [
                            {
                                "text": build_conversation_prompt(session, kpis)
                                if is_conversation
                                else build_fixed_prompt(session, kpis)
                            }
                        ],
                    }
                ],
                response_mime_type="application/json",
                response_schema=_score_schema(by_index=is_conversation),
            )
            raw = json.loads(text or "{}")
            report = (
                assemble_conversation_from_model(session, template, raw)
                if is_conversation
                else assemble_from_model(session, template, raw)
            )
            return await _with_sentiment(settings, session, report, is_conversation)
        except Exception as exc:  # noqa: BLE001 - degrade rather than lose the report
            logger.error("model scoring failed, using heuristic fallback: %s", exc)

    report = (
        heuristic_conversation_report(session, template)
        if is_conversation
        else heuristic_report(session, template)
    )
    return await _with_sentiment(settings, session, report, is_conversation)


async def _with_sentiment(
    settings: Settings, session: dict, report: dict, is_conversation: bool
) -> dict:
    """Attach the communication read, for conversation tracks only.

    Best-effort: a scorecard is still useful without it. Fixed-slot tracks are skipped
    because a typed answer's "tone" is a much weaker signal than a spoken one's, and
    presenting it identically would overstate it.
    """
    if not is_conversation:
        return report
    sentiment = await signals.analyze_sentiment(settings, session)
    if sentiment:
        report["sentiment"] = sentiment
    return report
