// lib/shared/widgets/mimic_wordmark.dart
//
// The app's in-UI branding is a text wordmark (no logo image is used anywhere
// in the app UI — assets/icon.png is only the OS app icon source, generated by scripts/gen-icons.py). This is the
// one shared widget for it, rather than a hand-rolled copy per screen.
//
// Plain ink, no two-tone split. The earlier `talbot`+`iq` treatment coloured
// the second half with colorScheme.primary, which under the block language
// would read as a block — and the wordmark is not the screen's one block. It
// also now matches web's MimicLockup, which sets the wordmark in bold ink and
// lets the mark beside it carry the identity.

import 'package:flutter/material.dart';

class MimicWordmark extends StatelessWidget {
  final double fontSize;

  const MimicWordmark({super.key, this.fontSize = 20});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Text(
      'Mimic',
      style: theme.textTheme.titleLarge?.copyWith(
        fontSize: fontSize,
        fontWeight: FontWeight.w700,
        letterSpacing: -0.5,
      ),
    );
  }
}
