// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF1O1SoXKv5iZ1RMaXQurVYwRSoT4ynqY',
    appId: '1:473028554722:web:152baa837fe77c7fb713bb',
    messagingSenderId: '473028554722',
    projectId: 'talbotiq-9cc4e',
    authDomain: 'talbotiq-9cc4e.firebaseapp.com',
    storageBucket: 'talbotiq-9cc4e.firebasestorage.app',
    measurementId: 'G-LGFED7318W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuzvsiUZcIOSJUairCLZpwOEwUYK8HQZw',
    appId: '1:473028554722:android:0eea71e6a072af23b713bb',
    messagingSenderId: '473028554722',
    projectId: 'talbotiq-9cc4e',
    storageBucket: 'talbotiq-9cc4e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPXGuAzCKRVszCFdJm3OEKYqb-q9QlKIs',
    appId: '1:473028554722:ios:aae697aede50212db713bb',
    messagingSenderId: '473028554722',
    projectId: 'talbotiq-9cc4e',
    storageBucket: 'talbotiq-9cc4e.firebasestorage.app',
    iosBundleId: 'com.example.talbotiqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPXGuAzCKRVszCFdJm3OEKYqb-q9QlKIs',
    appId: '1:473028554722:ios:aae697aede50212db713bb',
    messagingSenderId: '473028554722',
    projectId: 'talbotiq-9cc4e',
    storageBucket: 'talbotiq-9cc4e.firebasestorage.app',
    iosBundleId: 'com.example.talbotiqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF1O1SoXKv5iZ1RMaXQurVYwRSoT4ynqY',
    appId: '1:473028554722:web:bd505d7ca9cbea75b713bb',
    messagingSenderId: '473028554722',
    projectId: 'talbotiq-9cc4e',
    authDomain: 'talbotiq-9cc4e.firebaseapp.com',
    storageBucket: 'talbotiq-9cc4e.firebasestorage.app',
    measurementId: 'G-N3P4TF77Q9',
  );
}
