"""Route-level checks against the in-memory store.

These exercise the paths the unit tests cannot: request validation, the store
write, and the response the browser actually receives.
"""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from app.main import create_app
from app.security import AuthedUser
from app.web.services import voice_jobs

VALID_LEAD = {
    "firstName": "Ada",
    "lastName": "Lovelace",
    "email": "Ada@Example.com",
    "hiresPerYear": "10-50",
}


# ── leads (public) ────────────────────────────────────────────────────────────


@pytest.fixture
def public_client() -> TestClient:
    return TestClient(create_app())


def test_a_lead_is_stored_and_acknowledged(public_client: TestClient, fake_store) -> None:
    response = public_client.post("/api/web/leads", json=VALID_LEAD)

    assert response.status_code == 201
    assert response.json() == {"ok": True}

    stored = list(fake_store.leads.docs.values())
    assert len(stored) == 1
    assert stored[0]["email"] == "ada@example.com"   # normalised
    assert stored[0]["source"] == "mimic-site"       # defaulted
    assert stored[0]["createdAt"]
    assert stored[0]["id"]                           # generated by the store


def test_leads_needs_no_token(public_client: TestClient) -> None:
    """Visitors filling in the marketing form are pre-login."""
    assert public_client.post("/api/web/leads", json=VALID_LEAD).status_code == 201


def test_an_invalid_lead_is_rejected_and_stores_nothing(
    public_client: TestClient, fake_store
) -> None:
    response = public_client.post(
        "/api/web/leads", json={**VALID_LEAD, "email": "not-an-email"}
    )
    assert response.status_code == 422
    assert "email" in response.json()["error"]
    assert fake_store.leads.docs == {}


def test_two_leads_do_not_collide(public_client: TestClient, fake_store) -> None:
    """Ids are generated per write; the same person submitting twice is two rows."""
    public_client.post("/api/web/leads", json=VALID_LEAD)
    public_client.post("/api/web/leads", json=VALID_LEAD)
    assert len(fake_store.leads.docs) == 2


# ── auth/me ───────────────────────────────────────────────────────────────────


def test_me_reports_the_role_from_firestore(authed_client: TestClient, monkeypatch) -> None:
    from app.web.services import users

    async def _recruiter(_settings, _uid):
        return users.RECRUITER

    async def _no_name(_settings, _uid):
        return None

    monkeypatch.setattr(users, "get_role", _recruiter)
    monkeypatch.setattr(users, "get_display_name", _no_name)

    body = authed_client.get("/api/web/auth/me").json()
    assert body["uid"] == "uid-recruiter"
    assert body["email"] == "recruiter@talbotiq.com"
    assert body["role"] == "recruiter"
    assert body["emailVerified"] is True
    assert body["status"] == "active"


def test_me_defaults_to_candidate_when_the_document_is_missing(
    authed_client: TestClient, monkeypatch
) -> None:
    """Least privilege — and the same default both clients' auth gates use."""
    from app.web.services import users

    async def _missing(_settings, _uid):
        return users.CANDIDATE

    async def _no_name(_settings, _uid):
        return None

    monkeypatch.setattr(users, "get_role", _missing)
    monkeypatch.setattr(users, "get_display_name", _no_name)

    assert authed_client.get("/api/web/auth/me").json()["role"] == "candidate"


def test_me_requires_a_token() -> None:
    client = TestClient(create_app())
    response = client.get("/api/web/auth/me")
    assert response.status_code == 401
    assert "error" in response.json()


# ── voices ────────────────────────────────────────────────────────────────────


def test_the_catalog_is_served_to_an_authenticated_caller(authed_client: TestClient) -> None:
    body = authed_client.get("/api/web/voices").json()
    assert len(body["voices"]) == 16
    assert len(body["personas"]) == 4
    assert body["voices"][0]["engine"] == "gemini_live"


def test_the_web_surface_has_no_voice_preview_route(authed_client: TestClient) -> None:
    """Deliberately absent: the browser mints from `/api/rt/gemini-preview-token`,
    whose setup builder already caps the text, locks the voice, and pins the
    read-once instruction. A web copy would be a second builder to keep in sync for
    no behavioural difference."""
    assert authed_client.post("/api/web/voices/Aoede/sample", json={}).status_code == 404


def test_the_shared_preview_token_route_is_reachable() -> None:
    """It is on the common surface, so it must still demand a real token — the web
    frontend gets no special path to it."""
    client = TestClient(create_app())
    response = client.post(
        "/api/rt/gemini-preview-token", json={"voice_name": "Aoede", "sample_text": "Hi"}
    )
    assert response.status_code == 401


# ── avatar ────────────────────────────────────────────────────────────────────


def test_status_reports_configured_services(authed_client: TestClient) -> None:
    body = authed_client.get("/api/web/avatar/status").json()
    # `tavus` joined when the Tavus key stopped being something a recruiter typed into
    # the browser: the client used to gate its avatar UI on the key it held locally,
    # so the page could report "configured" for a credential the server had never seen.
    assert set(body) == {"deepgram", "hume", "gemini", "rekognition", "tavus"}
    assert all(isinstance(value, bool) for value in body.values())


def test_a_tiny_frame_is_skipped_without_an_api_call(authed_client: TestClient) -> None:
    """200 with `success: false`, which the client treats as a skipped frame — and
    the correlation fields come back so it can line the result up."""
    response = authed_client.post(
        "/api/web/avatar/analyze-face",
        json={"imageBase64": "A" * 100, "questionIdx": 2, "timestampMs": 1234},
    )
    assert response.status_code == 200
    assert response.json() == {
        "success": False,
        "reason": "frame_too_small",
        "questionIdx": 2,
        "timestampMs": 1234,
    }


def test_a_missing_frame_is_a_400_with_the_success_flag(authed_client: TestClient) -> None:
    response = authed_client.post("/api/web/avatar/analyze-face", json={})
    assert response.status_code == 400
    assert response.json()["success"] is False


def test_gemini_generate_rejects_a_bad_model(authed_client: TestClient) -> None:
    response = authed_client.post(
        "/api/web/avatar/gemini-generate",
        json={"model": "gpt-4", "requestBody": {"contents": []}},
    )
    assert response.status_code == 400
    assert response.json()["error"] == "Invalid model name"


def test_gemini_generate_requires_a_request_body(authed_client: TestClient) -> None:
    response = authed_client.post(
        "/api/web/avatar/gemini-generate", json={"model": "gemini-2.5-flash"}
    )
    assert response.status_code == 400
    assert response.json()["error"] == "Missing requestBody"


def test_an_expired_local_voice_job_reports_failed_with_a_200(
    authed_client: TestClient,
) -> None:
    """The client polls this for minutes and retries a 404, so a terminal state in a
    200 is what makes it stop instead of hanging behind a spinner."""
    body = authed_client.get("/api/web/avatar/hume/jobs/gemvoice-gone").json()
    assert body["status"] == voice_jobs.FAILED
    assert "no longer exists" in body["error"]


def test_an_unfinished_local_job_predictions_fetch_is_a_409(
    authed_client: TestClient, fake_store
) -> None:
    fake_store.voice_jobs.docs["gemvoice-1"] = {
        "id": "gemvoice-1",
        "status": voice_jobs.IN_PROGRESS,
        "createdAt": "2999-01-01T00:00:00+00:00",
    }
    response = authed_client.get("/api/web/avatar/hume/jobs/gemvoice-1/predictions")
    assert response.status_code == 409
    assert "IN_PROGRESS" in response.json()["error"]


def test_a_completed_local_job_returns_its_predictions(
    authed_client: TestClient, fake_store
) -> None:
    import json

    payload = [{"source": {"type": "file", "filename": "x.webm"}}]
    fake_store.voice_jobs.docs["gemvoice-2"] = {
        "id": "gemvoice-2",
        "status": voice_jobs.COMPLETED,
        "predictions": json.dumps(payload),
        "createdAt": "2999-01-01T00:00:00+00:00",
    }
    response = authed_client.get("/api/web/avatar/hume/jobs/gemvoice-2/predictions")
    assert response.status_code == 200
    assert response.json() == payload


def test_hume_routes_need_a_key_for_a_non_local_job(authed_client: TestClient) -> None:
    """A real Hume id with no key configured is a clear 400, not a confusing proxy
    error."""
    response = authed_client.get("/api/web/avatar/hume/jobs/real-hume-id")
    assert response.status_code == 400
    assert "not configured" in response.json()["error"]


# ── help ──────────────────────────────────────────────────────────────────────


def test_chat_always_returns_200_even_when_the_model_fails(
    authed_client: TestClient, monkeypatch
) -> None:
    """This is a chat window: an error status turns it into a dead box the user
    cannot recover from without a reload."""
    from app.web.services import mimic_guide

    async def _boom(*args, **kwargs):
        raise RuntimeError("model exploded")

    monkeypatch.setattr(mimic_guide, "run", _boom)
    response = authed_client.post(
        "/api/web/help/chat", json={"messages": [{"role": "user", "content": "hi"}]}
    )
    assert response.status_code == 200
    assert response.json()["reply"] == "Something went wrong. Please try again."


def test_chat_rejects_an_empty_history(authed_client: TestClient) -> None:
    assert authed_client.post("/api/web/help/chat", json={"messages": []}).status_code == 422


def test_agent_tolerates_an_empty_turn(authed_client: TestClient) -> None:
    """One blank message must not reject the request — that would fail every later
    turn and brick the session."""
    response = authed_client.post(
        "/api/web/help/agent",
        json={
            "messages": [{"role": "user", "content": ""}],
            "context": {"route": "/analytics", "availableActions": [], "state": {}},
        },
    )
    assert response.status_code == 200
    assert response.json()["awaitingUser"] is True


def test_tts_token_mints_a_locked_grant(authed_client: TestClient, monkeypatch) -> None:
    """The browser connects to Google itself, so what this returns IS the whole
    session — the setup must be locked into the token, not sent by the client."""
    from datetime import datetime, timezone

    from app.providers import gemini as provider_gemini
    from app.web.routes import help as help_route

    captured: dict = {}

    class _FakeToken:
        token = "auth_tokens/abc"
        ws_url = "wss://example.invalid/live"
        model = "models/fake-live"
        expires_at = datetime(2026, 1, 1, tzinfo=timezone.utc)
        connect_by = datetime(2026, 1, 1, tzinfo=timezone.utc)

    class _FakeClient:
        def __init__(self, settings):
            self.settings = settings

        async def mint_live_token(self, setup, *, session_minutes, uses=1):
            captured["setup"] = setup
            captured["session_minutes"] = session_minutes
            captured["uses"] = uses
            return _FakeToken()

    monkeypatch.setattr(help_route, "GeminiClient", _FakeClient)

    response = authed_client.post(
        "/api/web/help/tts-token",
        json={"text": "Go to Sessions to create an interview.", "lang": "hi"},
    )
    assert response.status_code == 200

    body = response.json()
    assert body["token"] == "auth_tokens/abc"
    assert body["wsUrl"] == "wss://example.invalid/live"
    assert set(body) == {"token", "wsUrl", "model", "expiresAt", "connectBy"}

    setup = captured["setup"]
    # Audio out, nothing listening.
    assert setup["generationConfig"]["responseModalities"] == ["AUDIO"]
    # The language is pinned, and the text is inside the setup rather than sent by
    # the client — that is what the lock protects.
    instruction = setup["systemInstruction"]["parts"][0]["text"]
    assert "in Hindi" in instruction
    assert "<read>Go to Sessions to create an interview.</read>" in instruction
    # One use, bounded session: a leaked token cannot fund an open-ended chat.
    assert captured["uses"] == 1
    assert 0 < captured["session_minutes"] <= 10


def test_tts_token_requires_a_token(authed_client: TestClient) -> None:
    client = TestClient(create_app())
    response = client.post(
        "/api/web/help/tts-token", json={"text": "hi", "lang": "en"}
    )
    assert response.status_code == 401


def test_tts_token_validates_its_input(authed_client: TestClient) -> None:
    for payload in [{"text": "", "lang": "en"}, {"text": "hi", "lang": "e"}, {"text": "hi"}]:
        assert authed_client.post("/api/web/help/tts-token", json=payload).status_code == 422


# ── face cache ────────────────────────────────────────────────────────────────


def test_face_cache_refuses_a_host_outside_the_allowlist(authed_client: TestClient) -> None:
    """Without the allowlist this endpoint would be an open proxy for any
    authenticated caller."""
    response = authed_client.get(
        "/api/web/avatar/face-cache", params={"url": "https://evil.example.com/a.mp4"}
    )
    assert response.status_code == 400
    assert response.json()["error"] == "Host not allowed"


def test_face_cache_refuses_plain_http(authed_client: TestClient) -> None:
    response = authed_client.get(
        "/api/web/avatar/face-cache", params={"url": "http://cdn.replica.tavus.io/a.mp4"}
    )
    assert response.status_code == 400


def test_face_cache_refuses_a_malformed_url(authed_client: TestClient) -> None:
    for url in ["", "not a url", "//no-scheme"]:
        response = authed_client.get("/api/web/avatar/face-cache", params={"url": url})
        assert response.status_code == 400, url


def test_face_cache_accepts_a_token_query_parameter() -> None:
    """A <video> element cannot set an Authorization header, so the token may ride in
    the query string for this one route. Here it is invalid, so a 401 proves the
    parameter was read and verified rather than ignored."""
    client = TestClient(create_app())
    response = client.get(
        "/api/web/avatar/face-cache",
        params={"url": "https://cdn.replica.tavus.io/a.mp4", "token": "not-a-real-token"},
    )
    assert response.status_code in (401, 503)


def test_face_cache_without_any_credential_is_401() -> None:
    client = TestClient(create_app())
    response = client.get(
        "/api/web/avatar/face-cache", params={"url": "https://cdn.replica.tavus.io/a.mp4"}
    )
    assert response.status_code == 401
