/**
 * MIMIC — the AI insight panel.
 *
 * A recruiter reading a report is looking at two very different kinds of claim
 * on one page: things the platform MEASURED (a timer, a score computed from
 * weights, whether a tab lost focus) and things a model INFERRED. Those must
 * never look the same, because only one of them is a judgement — and the whole
 * premise of the product is that a human makes the decision with the evidence
 * in front of them.
 *
 * So machine-written content gets its own surface, and it is recognisable in
 * one glance from across the room:
 *
 *   · the signal mark, in its idle state — the same mark the interview room uses
 *   · a signal line down the leading edge, in the machine-presence accent
 *   · a tinted ground, one step off the panel it sits on
 *   · the provenance said in WORDS, not only in colour
 *
 * It is deliberately NOT a chat bubble. A chat bubble implies a conversation
 * partner whose claims you accept or reject socially; this is a filed
 * observation with a source, which is the relationship we actually want.
 *
 * Everything here is static by default. An insight panel that animates on every
 * report render would be a page full of movement — the mark's idle state is a
 * composed still frame, and that is the point.
 */
import type { ReactNode } from 'react'
import { cn } from '@/components/ui/cn'
import { AISignal } from './AISignal'

export function AIInsight({
  title = 'AI summary',
  provenance = 'Generated by the scoring model from this interview’s transcript.',
  children,
  action,
  className,
}: {
  /** The panel's heading. Short — it labels the surface, not the content. */
  title?: string
  /**
   * One line stating where this came from. Required by construction: a machine
   * claim without a stated source is exactly what this component exists to
   * prevent. Pass `null` only when the surrounding panel already says it.
   */
  provenance?: string | null
  children: ReactNode
  /** An optional affordance — "See the evidence", "Regenerate". */
  action?: ReactNode
  className?: string
}) {
  return (
    <section
      className={cn(
        'relative overflow-hidden rounded-lg border border-ai-rule bg-ai-bg',
        // The signal line: a 2px edge in the machine accent, drawn inside the
        // border box so it cannot shift the panel's geometry.
        'before:absolute before:inset-y-0 before:left-0 before:w-[2px] before:bg-ai before:content-[""]',
        className,
      )}
    >
      <div className="flex items-start gap-3 px-4 py-3.5 sm:px-5">
        <AISignal state="idle" size={26} className="mt-0.5" />

        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
            <h3 className="text-[13px] font-bold uppercase tracking-[0.08em] text-ai">
              {title}
            </h3>
            {action && <div className="flex-shrink-0">{action}</div>}
          </div>

          <div className="measure mt-2 text-[15px] leading-relaxed text-ink-body">
            {children}
          </div>

          {provenance && (
            <p className="mt-3 border-t border-ai-rule pt-2.5 text-xs leading-relaxed text-ink-muted">
              {provenance}
            </p>
          )}
        </div>
      </div>
    </section>
  )
}

/**
 * A single observation inside an insight — a strength, a concern, a
 * recommendation. `tone` is carried by a glyph and a word as well as a colour,
 * so it survives export, print and monochrome.
 */
export function AIObservation({
  tone = 'neutral',
  children,
}: {
  tone?: 'strength' | 'concern' | 'neutral'
  children: ReactNode
}) {
  const mark = {
    strength: { glyph: '+', cls: 'text-ok', label: 'Strength' },
    concern: { glyph: '!', cls: 'text-warn', label: 'Concern' },
    neutral: { glyph: '·', cls: 'text-ink-faint', label: 'Observation' },
  }[tone]

  return (
    <li className="flex items-start gap-2.5 text-sm leading-relaxed text-ink-body">
      <span className={cn('mt-px flex-none font-mono text-sm font-bold', mark.cls)} aria-hidden="true">
        {mark.glyph}
      </span>
      <span className="sr-only">{mark.label}: </span>
      <span className="min-w-0">{children}</span>
    </li>
  )
}
