// test/mcq_contract_test.dart
//
// The Dart half of the MCQ paper golden contract.
//
// Every other contract in `contracts/` pins field NAMES so two clients agree on a
// shape. This one pins an ABSENCE.
//
// MCQ is the only track whose stored questions contain the answers. The server projects
// a paper through an allow-list (`mcq_public_question`, backend/app/mcq_scoring.py) so
// `correctOptionIds` and `correctPairs` never reach a device. The Python side asserts
// that on the serialised bytes leaving the server; this side asserts the other half —
// that the READER has nowhere to put a key even if one arrived, and that everything the
// candidate legitimately needs does survive the parse.
//
// The fixture is generated by the backend:
//
//   REGENERATE_MCQ_FIXTURES=1 pytest tests/test_mcq_contract.py
//
// Update both suites in the same commit.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:talbotiq/features/interviews/candidate/mcq/mcq_models.dart';

File _fixtureFile() {
  final candidates = [
    File('../contracts/mcq_paper.fixtures.json'),
    File('contracts/mcq_paper.fixtures.json'),
  ];
  return candidates.firstWhere(
    (f) => f.existsSync(),
    orElse: () => throw StateError(
      'contracts/mcq_paper.fixtures.json not found. Generate it with '
      'REGENERATE_MCQ_FIXTURES=1 pytest tests/test_mcq_contract.py in backend/.',
    ),
  );
}

/// Field names that carry the answer key, in either question shape.
const _keyFields = ['correctOptionIds', 'correctPairs', 'explanation', 'internalNote'];

void main() {
  late Map<String, dynamic> fixture;
  late Map<String, dynamic> publicPaper;
  late McqPaper paper;

  setUpAll(() {
    fixture = jsonDecode(_fixtureFile().readAsStringSync()) as Map<String, dynamic>;
    publicPaper = Map<String, dynamic>.from(fixture['publicPaper'] as Map);
    paper = McqPaper.fromJson({
      'interviewId': 'interview-1',
      'name': 'Backend Screening',
      ...publicPaper,
    });
  });

  group('the answer key never reaches this client', () {
    test('the fixture the server would send carries no key', () {
      // The Python suite asserts this on its own output. Asserting it again here is
      // not duplication: it proves the file the DART side is reading is the same
      // clean one, so a fixture regenerated from a leaking projection fails in both
      // languages rather than only in the one somebody remembered to run.
      final wire = jsonEncode(publicPaper);
      for (final field in _keyFields) {
        expect(wire.contains(field), isFalse,
            reason: '$field is in the paper the server sends');
      }
    });

    test('the model has no field a key could be parsed into', () {
      // A key smuggled onto the wire must not survive the parse. This is the part the
      // Python side cannot assert: it is a property of the READER.
      final leaking = <String, dynamic>{
        'id': 'q-leak',
        'text': 'Which is prime?',
        'type': 'single',
        'options': [
          {'id': 'a', 'text': '4'},
          {'id': 'b', 'text': '7'},
        ],
        'correctOptionIds': ['b'],
        'correctPairs': {'p': 'm'},
        'explanation': 'because 7 is prime',
        'internalNote': 'swap next cycle',
      };
      final question = McqQuestion.fromJson(leaking);

      // Everything the model exposes, serialised. If a future field mirrored a
      // stored-only one, the value would show up here.
      final reachable = jsonEncode({
        'id': question.id,
        'text': question.text,
        'type': question.type.name,
        'options': [
          for (final o in question.options) {'id': o.id, 'text': o.text},
        ],
        'prompts': [
          for (final o in question.prompts) {'id': o.id, 'text': o.text},
        ],
        'matches': [
          for (final o in question.matches) {'id': o.id, 'text': o.text},
        ],
        'code': question.code,
        'points': question.points,
      });

      expect(reachable.contains('because 7 is prime'), isFalse);
      expect(reachable.contains('swap next cycle'), isFalse);
      // The option ids themselves legitimately appear — they name what the candidate
      // picks from. What must not survive is any MARKING of which one is right.
      for (final field in _keyFields) {
        expect(reachable.contains(field), isFalse);
      }
    });
  });

  group('the paper parses into something answerable', () {
    test('every question the server published is readable', () {
      final serverQuestions = (publicPaper['questions'] as List).length;
      expect(paper.questions.length, serverQuestions);
      expect(paper.total, serverQuestions);
      for (final question in paper.questions) {
        expect(question.id, isNotEmpty);
        expect(question.text, isNotEmpty);
      }
    });

    test('each question type maps to an input this client can render', () {
      final byId = {for (final q in paper.questions) q.id: q};

      expect(byId['q-single']!.type, McqQuestionType.single);
      expect(byId['q-single']!.options, hasLength(4));

      expect(byId['q-multi']!.type, McqQuestionType.multi);

      // A code-reading question is a single-select with a snippet. The snippet is
      // visible by necessity — the question cannot be answered without it.
      expect(byId['q-code']!.code, isNotNull);
      expect(byId['q-code']!.type, McqQuestionType.single);

      final match = byId['q-match']!;
      expect(match.isPairing, isTrue);
      expect(match.prompts, hasLength(3));
      expect(match.matches, hasLength(3));
      // Both columns arrive, and neither is annotated with which row goes where.
      expect(match.options, isEmpty);
    });

    test('an unknown question type renders as single-select rather than vanishing', () {
      // A build that has not learned a type yet is still marking the candidate on it.
      // Hiding the question is wrong in the SCORE; showing the wrong input is wrong
      // only in the widget, and recoverable.
      final question = McqQuestion.fromJson({
        'id': 'q-future',
        'text': 'Rank these',
        'type': 'ordering',
        'options': [
          {'id': 'a', 'text': 'One'},
        ],
      });
      expect(question.type, McqQuestionType.single);
      expect(question.options, hasLength(1));
    });

    test('sections carry their questions, their instructions and their passage', () {
      expect(paper.isDivided, isTrue);
      final aptitude = paper.sections.first;
      expect(aptitude.name, 'Aptitude');
      expect(aptitude.instructions, isNotNull);
      expect(aptitude.passage, isNotNull);
      expect(paper.questionsIn(aptitude).map((q) => q.id), ['q-single']);
    });

    test('a question named by no section is still on the paper', () {
      // Dropping it would score the candidate zero on a question they were never
      // shown, and the paper would simply look shorter than the recruiter built.
      expect(paper.unsectioned.map((q) => q.id), contains('q-unsectioned'));
      final rendered = {
        for (final s in paper.sections) ...paper.questionsIn(s).map((q) => q.id),
        ...paper.unsectioned.map((q) => q.id),
      };
      expect(rendered, paper.questions.map((q) => q.id).toSet());
    });

    test('an undivided paper reports itself as one', () {
      final flat = McqPaper.fromJson({
        'interviewId': 'i',
        'questions': publicPaper['questions'],
      });
      expect(flat.isDivided, isFalse);
      expect(flat.unsectioned, isEmpty, reason: 'nothing is orphaned when nothing is sectioned');
    });

    test('a submitted attempt is recognised from either signal', () {
      // `status` is the field the runtime sets; `submittedAt` is what a partially
      // written document from an older build might carry alone. Either one means the
      // paper is closed, and treating a submitted paper as answerable would let a
      // candidate change answers behind a score that is already stored.
      expect(
        McqPaper.fromJson({'interviewId': 'i', 'status': 'submitted'}).submitted,
        isTrue,
      );
      expect(
        McqPaper.fromJson({'interviewId': 'i', 'submittedAt': '2026-01-01T00:00:00Z'})
            .submitted,
        isTrue,
      );
      expect(
        McqPaper.fromJson({'interviewId': 'i', 'status': 'in_progress'}).submitted,
        isFalse,
      );
    });
  });
}
